name: AWS Startup Community Conference 2022　Call for Papers 応募フォーム
description: AWS Startup Community Conference 2022 Call for Papers へのご応募をご検討頂きありがとうございます。下記のフォームに必要事項をご記入の上、Submitしてください。
title: "<セッションタイトルを最大40文字程度で記入してください>"
labels: [cfp]
assignees:
  - sumi-biztech
  - kzk-maeda
  - isasenth
  - xhiroga
body:
  - type: checkboxes
    id: terms
    attributes:
      label: AWS 行動規範 (Code of Conduct) への同意 (必須)
      description: セッションの応募にはイベント登録規約、および AWS 行動規範 Code of Conduct への同意が必要です
      options:
        - label: 私は、[AWS 行動規範 (Code of Conduct)](https://aws.amazon.com/jp/codeofconduct/) を確認し、同意しました
          required: true
  - type: input
    id: contact
    attributes:
      label: Twitter ID (必須)
      description: Twitter ID (ダイレクトメッセージ可能なもの)をご記入ください。採択後、運営よりダイレクトメッセージにてご連絡します
      placeholder: ここに Twitter ID をご記入ください
    validations:
      required: true
  - type: checkboxes
    id: session-title
    attributes:
      label: セッションタイトル (必須)
      options:
        - label: セッションのタイトルをイシュー件名に最大40文字程度で入力しました
          required: true
  - type: textarea
    id: session-abstract
    attributes:
      label: セッションのアブストラクト (最大250文字) (必須)
      description: 採択の場合、原則としてこのままセッション情報として Web に掲載されます
      placeholder: ここにセッション アブストラクトをご記入ください
    validations:
      required: true
  - type: textarea
    id: session-detail
    attributes:
      label: セッションについての補足情報 (最大800文字) (任意)
      description: セッション内容についてタイトルおよびアブストラクトのみで説明しきれない場合、補足情報を800文字以下にて記入してください
      placeholder: ここにセッションの補足説明をお書きください
    validations:
      required: false
  - type: dropdown
    id: session-speaker-phase
    attributes:
      label: 登壇者の所属するスタートアップのフェーズ （必須）
      options:
        - Seed
        - series A
        - series B
        - series C
        - series D 以降
        - VC / 投資家
        - その他
    validations:
      required: true
  - type: dropdown
    id: session-expected-attendee-phase
    attributes:
      label: 想定受講者のスタートアップのフェーズ (複数選択可) (必須)
      multiple: true
      options:
        - Seed
        - series A
        - series B
        - series C
        - series D 以降
    validations:
      required: true
  - type: dropdown
    id: session-expected-attendee-roles
    attributes:
      label: 想定受講者の開発対象やロール・役割 (複数選択可) (必須)
      multiple: true
      options:
        - Web フロントエンド開発
        - Web バックエンド / サーバーサイド開発
        - モバイル / ネイティブアプリケーション開発
        - DevOps / Infrastructure as Code
        - 機械学習モデル開発
        - その他
    validations:
      required: true
  - type: dropdown
    id: session-topics
    attributes:
      label: セッションのトピック (複数選択可) (必須)
      multiple: true
      options:
        - プログラミング
        - アプリケーションアーキテクチャー
        - ソフトウェアテスト
        - 開発プロセス
        - エンジニアのキャリア
        - エンジニア組織のカルチャー
        - その他
    validations:
      required: true
  - type: dropdown
    id: session-format
    attributes:
      label: セッションのフォーマット (必須)
      options:
        - スライドを映しながら話す、通常セッション
        - 対談形式
        - パネルディスカッション
        - その他
    validations:
      required: true
